blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/detail/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('blog/pub',views.pub_blog, name='pub_blog'),
    path('blog/comment/pub',views.pub_comment, name='pub_comment'),
    path('search/',views.search, name='search'),
]

blogdemo/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('blog.urls')),
    path('auth/',include('zlauth.urls'))
]

zlauth/urls.py
from django.urls import path
from . import views
app_name = 'zlauth'
urlpatterns = [
    path('login/', views.zllogin, name='login'),
    path('register/', views.register, name='register'),
    path('captcha/', views.send_email_captcha, name='email_captcha'),
    path('logout/', views.zllogout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-知了博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height="40">
                </img>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                    <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}">
                    <input type="search" class="form-control " placeholder="搜索..."
                           aria-label="Search"  name="q" method="GET">
                </form>
                {% if user.is_authenticated %}
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'image/avatar.webp' %}" alt="mdo" width="32" height="32"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small" style="">
                            <li><a class="dropdown-item" href="{% url 'zlauth:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="text-end">
                        <a href="{% url 'zlauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                        <a href="{% url 'zlauth:register' %}" type="button" class="btn btn-primary">注册</a>
                    </div>
                {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% block title %}博客详情{% endblock %}
{% block head %}
    <script src="{% static 'highlight/styles/default.min.css' %}"></script>
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}
{% block main %}
    <h1>{{ blog.title }}</h1>
    <div class="mt-2">
        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" alt="" width="30px" height="30px">
        <span class="ms-2">{{ bloh.author.username }}</span>
        <span clss="ms-2">于</span>
        <span clss="ms-2">{{ blog.pubt_time|date:"Y年m月d日 h时i分"}}</span>
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论 {{ blog.comments.all|length }} </h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item mb-3">
                    <div class="d-flex justify-content-between">
                        <div class="user-info">
                            <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" alt="" width="50px"
                                 height="50px">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="create-time" style="line-height: 40px">{{ comment.pub_time|date:"Y年m月d日 h时i分"}}</div>
                    </div>
                    <div class="mt-2">
                        {{ comment.content }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
    hljs.highlightAll();
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for blog in blogs %}
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height:100px;">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200}}</p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" alt="" width="30px"
                             height="30px">
                        {{ blog.author.username }}
                    </div>
                    <div>
                        发布时间:{{ blog.pubt_time|date:"Y年m月d日 h时i分"}}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block main%}
    <div style="max-width:330px ;" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" class="form-control" name="email" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label for="">密码</label>
                <input type="password" class="form-control" name="password" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="flexCheckDefault" name="remerber" value="1">
                <label for="flexCheckDefault" class="form-check-label">记住我</label>
            </div>
            <div class="mb-3 ">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/pub_blog.html
  {% extends 'base.html' %}
{% block title %}发布博客{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 100;
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}
{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor-wrapper">
                    <div id="toolbar-container"></div>
                    <div id="editor-container"></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" type="button" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block main %}
    <div style="max-width:330px ;" class="m-auto">
        <h1>注册</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" class="form-control" name="username" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" class="form-control" name="email" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码"
                           aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" class="form-control" name="password" placeholder="密码">
            </div>
            <div class="mb-3 ">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}